repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-json
    - id: check-merge-conflict
    - id: check-shebang-scripts-are-executable
    - id: check-yaml
    - id: end-of-file-fixer
    - id: forbid-submodules
    - id: requirements-txt-fixer
    - id: trailing-whitespace

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy
    additional_dependencies:
      - "semver>=3,<4"
      - "click>=8,<9"
      - "setuptools>=69,<70"
    pass_filenames: false # This and the args, argument are needed to make mypy read pyproject.toml
    args: ["."]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.1
  hooks:
  - id: ruff
    args: [ --fix ]

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v17.0.6
  hooks:
  - id: clang-format
