[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
extend-exclude = [
    "src",
    "doc",
    "include",
    "lib",
    "scripts/menuconfig.py",
    "scripts/kconfiglib.py",
    "scripts/genconfig.py"
]

[tool.ruff.lint]
select = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.mypy]
warn_return_any = true
exclude = [
    "^build.*",
    "^doc.*",
    "^scripts/menuconfig\\.py$"
]
