/**
 * Punch BOOT
 *
 * Copyright (C) 2018 Jonas Blixt <jonpe960@gmail.com>
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

#ifndef INCLUDE_PB_ERRORS_H_
#define INCLUDE_PB_ERRORS_H_

enum pb_errors {
    PB_OK = 0,
    PB_ERR,
    PB_ERR_TIMEOUT,
    PB_ERR_KEY_REVOKED,
    PB_ERR_SIGNATURE,
    PB_ERR_CHECKSUM,
    PB_ERR_MEM,
    PB_ERR_IO,
    PB_ERR_NOT_FOUND,
    PB_ERR_NOT_IMPLEMENTED,
    PB_ERR_BUF_TOO_SMALL, /* 10 */
    PB_ERR_ABORT,
    PB_ERR_NOT_AUTHENTICATED,
    PB_ERR_AUTHENTICATION_FAILED,
    PB_ERR_INVALID_ARGUMENT,
    PB_ERR_INVALID_COMMAND,
    PB_ERR_PART_NOT_FOUND,
    PB_ERR_PART_NOT_BOOTABLE,
    PB_ERR_PARAM,
    PB_ERR_NOT_SUPPORTED,
    PB_ERR_AGAIN, /* 20 */
    PB_ERR_STATE,
    PB_ERR_BAD_HEADER,
    PB_ERR_BAD_KEYSTORE,
    PB_ERR_KEY_NOT_FOUND,
    PB_ERR_UNKNOWN_HASH,
    PB_ERR_BAD_META,
    PB_ERR_BAD_PAYLOAD,
    PB_ERR_NO_ACTIVE_BOOT_PARTITION,
    PB_ERR_ASN1,
};

#endif  // INCLUDE_PB_ERRORS_H_
