name: Punchboot-tools build

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install deps
      run: |
          sudo apt-get update
          sudo apt-get install libusb-1.0-0 libusb-1.0-0-dev uuid-runtime uuid-dev lcov libmbedtls-dev liblzma-dev
    - name: Build BPAK
      run: |
            git clone https://github.com/jonasblixt/bpak --depth 1 --branch v0.7.0
            pushd bpak
            cmake -B build/
            make -C build/ -j$(nproc)
            sudo make -C build/ install
            sudo ldconfig
            popd
    - name: Build punchboot-tools
      run: |
            cmake -B build/ -DPB_TOOLS_BUILD_TOOL=1 -DPB_TOOLS_BUILD_SOCKET=1 -DPB_TOOLS_BUILD_TESTS=1 -DPB_TOOLS_BUILD_PYTHON_WRAPPER=1
            make -C build/ -j$(nproc)
            ctest -j$(nproc) --output-on-failure --test-dir build
            lcov --directory build --capture --output-file coverage.info
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
  build-windows:
    runs-on: windows-latest
    name: windows-build
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: 'Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        install: gcc make cmake libutil-linux-devel libutil-linux mingw-w64-x86_64-libusb
    - name: 'Clone repos'
      shell: pwsh
      run: |
        git clone https://github.com/jonasblixt/bpak --depth 1 --branch 0.8.2-work
    - name: 'Build BPAK'
      run: |
        pushd bpak
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DBPAK_BUILD_MINIMAL=1
        make -C build
        make -C build install
        popd
    - name: Build punchboot-tools
      run: |
        export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/share/pkgconfig
        set
        ls /usr/local/lib
        cmake -B build/ -DPB_TOOLS_BUILD_TOOL=1 -DPB_TOOLS_BUILD_SOCKET=0 -DPB_TOOLS_BUILD_TESTS=0 -DPB_TOOLS_BUILD_PYTHON_WRAPPER=0
        make -C build/ -j$(nproc)
