name: Punchboot-tools build

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    name: linux-build
    steps:
    - uses: actions/checkout@v1
    - name: Install deps
      run: |
          sudo apt-get update
          sudo apt-get install libusb-1.0-0 libusb-1.0-0-dev lcov libmbedtls-dev liblzma-dev
    - name: Build BPAK
      run: |
            git clone https://github.com/jonasblixt/bpak --depth 1 --branch v0.9.2
            pushd bpak
            cmake -B build/
            make -C build/ -j$(nproc)
            sudo make -C build/ install
            sudo ldconfig
            popd
    - name: Build punchboot-tools
      run: |
            cmake -B build/ -DPB_TOOLS_BUILD_TOOL=1 -DPB_TOOLS_BUILD_SOCKET=1 -DPB_TOOLS_BUILD_TESTS=1
            make -C build/ -j$(nproc)
            ctest -j1 --output-on-failure --test-dir build
            lcov --directory build --capture --output-file coverage.info
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
