name: Punchboot-tools build

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install deps
      run: |
          sudo apt-get update
          sudo apt-get install autoconf-archive libusb-1.0-0 libusb-1.0-0-dev uuid-runtime uuid-dev lcov libmbedtls-dev liblzma-dev
    - name: Build BPAK
      run: |
            git clone https://github.com/jonasblixt/bpak --depth 1 --branch v0.6.2
            pushd bpak
            autoreconf -fi
            ./configure
            make
            sudo make install
            sudo ldconfig
            popd
    - name: Build punchboot-tools
      run: |
            autoreconf -fi
            ./configure --enable-code-coverage
            make check-code-coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
