name: Punchboot-tools coverity

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install deps
      run: |
          sudo apt-get update
          sudo apt-get install autoconf-archive libusb-1.0-0 libusb-1.0-0-dev uuid-dev lcov libmbedtls-dev liblzma-dev
    - name: Build BPAK
      run: |
            git clone https://github.com/jonasblixt/bpak --depth 1 --branch v0.6.3
            pushd bpak
            autoreconf -fi
            ./configure
            make
            sudo make install
            sudo ldconfig
            popd
    - name: Configure punchboot-tools
      run: |
            autoreconf -fi
            ./configure --enable-code-coverage
    - name: Download Coverity Build Tool
      run: |
        wget -q https://scan.coverity.com/download/cxx/linux64 --post-data "token=$TOKEN&project=jonasblixt%2Fpunchboot-tools" -O cov-analysis-linux64.tar.gz
        mkdir cov-analysis-linux64
        tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
      env:
        TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
    - name: Build with cov-build
      run: |
        export PATH=`pwd`/cov-analysis-linux64/bin:$PATH
        make clean
        cov-configure --template --compiler gcc --comptype gcc
        cov-build --dir cov-int make
    - name: Submit the result to Coverity Scan
      run: |
        tar czvf pb.tgz cov-int
        curl \
          --form project=jonasblixt%2Fpunchboot-tools \
          --form token=$TOKEN \
          --form email=jonpe960@gmail.com \
          --form file=@pb.tgz \
          --form version=master \
          --form description="punchboot-tools" \
          https://scan.coverity.com/builds?project=jonasblixt%2Fpunchboot-tools
      env:
        TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
