name: Punchboot-tools build (Windows)

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    name: windows-build
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: 'Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        install: |
          make
          cmake
          wget
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-libusb
    - name: 'Clone repos'
      shell: pwsh
      run: |
        git clone https://github.com/jonasblixt/bpak --depth 1 --branch v0.8.2
    - name: 'Build BPAK'
      run: |
        pushd bpak
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DBPAK_BUILD_MINIMAL=1
        make -C build
        make -C build install
        popd
    - name: Build punchboot-tools
      run: |
        export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig
        cmake -B build/ -DPB_TOOLS_BUILD_TOOL=1 -DPB_TOOLS_BUILD_SOCKET=0 -DPB_TOOLS_BUILD_TESTS=0 -DPB_TOOLS_BUILD_PYTHON_WRAPPER=0 -DPB_TOOLS_BUILD_STATIC=1
        make -C build/ -j$(nproc)
